version: '2'
networks:
  backend:
    external:
      name: caddy_backend

services:
  dokuwiki:
    networks:
      - backend
    expose:
      - 80
    build:
      context: ./docker/
      dockerfile: Dockerfile
    # volumes:
    #   - ./conf/:/dokuwiki-conf/
    #   - ./data/:/dokuwiki-data/
