version: "2"
networks:
  backend:
    external:
      name: caddy_backend


services:
  caddy:
    build:
      context: caddy/
      dockerfile: Dockerfile
    image: firecyberice/caddy:dirty
    command: -http2=false -conf /root/.caddy/conf/caddyfile
    restart: always
    #    read_only: true
    cap_add:
      - NET_BIND_SERVICE
    user: root
    ports:
      - 80:80
      - 443:443
    networks:
      - backend
    volumes:
      - ./caddy/:/root/.caddy:rw
